// Generated by Haxe 4.3.4
(function ($global) { "use strict";
var preact_Component = require("preact").Component;
class TestComponent extends preact_Component {
	constructor(props,context) {
		super(props,context);
	}
	render(props,state,context) {
		return <p>hi chat</p>;
	}
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
{
}
})({});
